Add ephemeral container
grafana/xk6-kubernetes pull request #34
Opened 2022-04-21 07:24 UTC by pablochacin

Add function to Pods for creating an ephemeral container in a running pod.
Also added a function for creating a pod to facilitate testing.

Note: tested with K8s cluster 1.23.x. Previous versions may not work or may need enabling ephemeral containers feature gate

2022-04-22 13:08 UTC, javaducky requested changes

2022-04-22 13:10 UTC, javaducky commented
Confirmed create and add with Kube v1.22.7 (`feature-gates=EphemeralContainers=true`).

2022-04-24 10:05 UTC, pablochacin commented on pkg/pods/pods.go
> +type ContainerOptions struct {
Hi @javaducky I added some comments, but I'm not sure what conventions is the project following in this regard. Could you please point me to some examples I can use as a reference?

2022-04-24 12:41 UTC, javaducky commented on pkg/pods/pods.go
> +type ContainerOptions struct {
Just standard documentation as described with [godoc](https://go.dev/blog/godoc) is fine. No need to worry about all the methods/types; just the new ones that you're adding.

We haven't been good at requiring this, but [xk6-sql](https://github.com/grafana/xk6-sql/blob/master/sql.go) is an example where I added documentation. You can always use `golint ./...` to check your progress.

2022-04-25 19:25 UTC, pablochacin commented on pkg/pods/pods.go
> +type ContainerOptions struct {
Added documentation.

2022-04-25 20:47 UTC, javaducky approved these changes

2022-04-25 20:47 UTC, merged

2022-04-25 20:48 UTC, javaducky commented
LGTM! Thank you @pablochacin .