Wait for ephemeral container
grafana/xk6-kubernetes pull request #61
Opened 2022-07-14 19:14 UTC by pablochacin

Add option for waiting for ephemeral container to be running

closes #60

2022-07-14 19:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-kubernetes?pullRequest=61) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-kubernetes?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-kubernetes?pullRequest=61) it.</sub>

2022-07-18 13:48 UTC, javaducky requested changes
Recommend using [Act](https://github.com/nektos/act) to run linter locally. There are some additional linting failures to cause your changes to fail upon merge.

`act --job run-golangci`

We should probably update our Github Actions to run the `run-golangci` job on creation of PRs rather than upon merge to `main`.

2022-07-18 13:48 UTC, javaducky commented on pkg/pods/pods.go
> +func (obj *Pods) AddEphemeralContainer(name, namespace string, options EphemeralContainerOptions) error {
API-breaking change for clients. Since it's early in the process for ephemeral containers, we should be fine.

2022-07-19 08:18 UTC, pablochacin commented on pkg/pods/pods.go
> +type PodConditionChecker func(*k8sTypes.Pod) (bool, error)
No it doesn't would change it to private to the package

2022-07-19 08:28 UTC, pablochacin commented on pkg/pods/pods.go
> +type EphemeralContainerOptions struct {
Done

2022-07-19 08:29 UTC, pablochacin commented on pkg/pods/pods.go
> +// waitForCondition watchs a Pod in a given namespace until a condition is validated by a PodConditionChecket or a timeout expires.
Fixed

2022-07-19 11:33 UTC, javaducky approved these changes
Verified changes will now pass linting. LGTM!

2022-07-19 11:33 UTC, merged